# Generated by Django 3.1.1 on 2020-11-18 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50, verbose_name='Місто')),
                ('code', models.CharField(max_length=10, verbose_name='Код')),
                ('country', models.CharField(max_length=50, verbose_name='Країна')),
                ('name', models.CharField(max_length=50, verbose_name='Назва')),
            ],
            options={
                'verbose_name': 'Аеропорт',
                'verbose_name_plural': 'Аеропорти',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency', models.CharField(max_length=50, verbose_name='Агенство')),
                ('company', models.CharField(max_length=100, verbose_name='Авіакомпанія')),
                ('departureTime', models.DateTimeField(verbose_name='Час відправлення')),
                ('destinationTime', models.DateTimeField(verbose_name='Час прибуття')),
                ('price', models.PositiveIntegerField(verbose_name='Ціна')),
                ('url', models.URLField(verbose_name='Посилання на купівлю')),
                ('departurePoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure_point', to='airtickets.airport')),
                ('destinationPoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_point', to='airtickets.airport')),
            ],
            options={
                'verbose_name': 'Квиток',
                'verbose_name_plural': 'Квитки',
            },
        ),
    ]
