# Generated by Django 3.1.1 on 2020-11-29 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Назва готелю')),
                ('description', models.TextField(verbose_name='Опис')),
                ('country', models.CharField(max_length=50, verbose_name='Назва зручності')),
                ('city', models.CharField(max_length=50, verbose_name='Назва зручності')),
                ('street', models.CharField(max_length=50, verbose_name='Назва зручності')),
                ('stars', models.PositiveSmallIntegerField(verbose_name='Зірки')),
                ('url', models.URLField(verbose_name='Посилання на бронь')),
            ],
            options={
                'verbose_name': 'Готель',
                'verbose_name_plural': 'Готелі',
            },
        ),
        migrations.CreateModel(
            name='HotelFacilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, verbose_name='Категорія')),
                ('name', models.CharField(max_length=50, verbose_name='Назва зручності')),
            ],
            options={
                'verbose_name': 'Зручність',
                'verbose_name_plural': 'Зручності',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='Тип кімнати')),
                ('description', models.TextField(verbose_name='Опис кімнати')),
                ('capacity', models.PositiveSmallIntegerField(verbose_name='Місткість кімнати')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.hotel')),
            ],
            options={
                'verbose_name': 'Кімната готелю',
                'verbose_name_plural': 'Кімнати готелів',
            },
        ),
        migrations.CreateModel(
            name='PlacesNearHotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=100, verbose_name='Мічце')),
                ('distance', models.FloatField(verbose_name='Відстань від готелю')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.hotel')),
            ],
            options={
                'verbose_name': 'Місце поруч з готелем',
                'verbose_name_plural': 'Місця поруч з готелемя',
            },
        ),
        migrations.CreateModel(
            name='HotelReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50, verbose_name='Автор')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('rating', models.FloatField(verbose_name='Рейтинг')),
                ('text', models.TextField(verbose_name='Текст відгуку')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.hotel')),
            ],
            options={
                'verbose_name': 'Відгук',
                'verbose_name_plural': 'Відгуки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HotelImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hotels/', verbose_name='Зображення')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.hotel')),
            ],
            options={
                'verbose_name': 'Зображення готелю',
                'verbose_name_plural': 'Зображення готелів',
            },
        ),
        migrations.AddField(
            model_name='hotel',
            name='facilities',
            field=models.ManyToManyField(to='hotels.HotelFacilities'),
        ),
    ]
