# Generated by Django 3.1.1 on 2020-11-29 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='price',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Вартість кімнати'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hotel',
            name='city',
            field=models.CharField(max_length=50, verbose_name='Місто'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='country',
            field=models.CharField(max_length=50, verbose_name='Країна'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='street',
            field=models.CharField(max_length=50, verbose_name='Вулиця'),
        ),
    ]
