# Generated by Django 3.1.1 on 2020-11-29 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_auto_20201129_1247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotelreview',
            old_name='tour',
            new_name='hotel',
        ),
    ]
