# Generated by Django 3.1.1 on 2020-11-28 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, verbose_name='Категорія')),
                ('name', models.CharField(max_length=50, verbose_name='Назва зручності')),
            ],
            options={
                'verbose_name': 'Зручність',
                'verbose_name_plural': 'Зручності',
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel', models.CharField(max_length=50, verbose_name='Готель')),
                ('country', models.CharField(max_length=50, verbose_name='Країна')),
                ('city', models.CharField(max_length=50, verbose_name='Місто')),
                ('stars', models.PositiveSmallIntegerField(verbose_name='Зірки')),
                ('image', models.ImageField(upload_to='tours/', verbose_name='Зображення')),
                ('facilities', models.ManyToManyField(to='tours.Facilities')),
            ],
            options={
                'verbose_name': 'Тур',
                'verbose_name_plural': 'Тури',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50, verbose_name='Автор')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('rating', models.FloatField(verbose_name='Рейтинг')),
                ('text', models.TextField(verbose_name='Текст відгуку')),
                ('tour', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tours.tour')),
            ],
            options={
                'verbose_name': 'Відгук',
                'verbose_name_plural': 'Відгуки',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(verbose_name='Ціна')),
                ('nights', models.PositiveSmallIntegerField(verbose_name='Кількість ночей')),
                ('meals', models.CharField(max_length=50, verbose_name='Харчування')),
                ('date', models.DateField(verbose_name='Дата вильоту')),
                ('agency', models.CharField(max_length=50, verbose_name='Турагенство')),
                ('url', models.URLField(verbose_name='Посиляння на бронювання')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.tour')),
            ],
            options={
                'verbose_name': 'Ціна',
                'verbose_name_plural': 'Ціни',
            },
        ),
    ]
