# Generated by Django 3.1.1 on 2020-11-29 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_review_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at'], 'verbose_name': 'Відгук', 'verbose_name_plural': 'Відгуки'},
        ),
    ]
